version: '3'

services:
    #PHP-FPM
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=symfony.local"
    volumes:
      - ./:/app
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
      - ~/.bash_history:/home/docker-user/.bash_history
    extra_hosts:
      - symfony.local:${DOCKER_HOST_IP}
    depends_on:
      - db
    networks:
      - local
      
  #NginX
  web:
    container_name: ${PROJECT_NAME}_web
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}-web.entrypoints=http
      - traefik.http.routers.${PROJECT_NAME}-web.rule=HostRegexp(`symfony.local`)
      - traefik.http.middlewares.${PROJECT_NAME}-web-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.${PROJECT_NAME}-web.middlewares=${PROJECT_NAME}-web-https-redirect
      - traefik.http.routers.${PROJECT_NAME}-web-secure.entrypoints=https
      - traefik.http.routers.${PROJECT_NAME}-web-secure.rule=HostRegexp(`symfony.local`)
      - traefik.http.routers.${PROJECT_NAME}-web-secure.tls=true
      - traefik.http.routers.${PROJECT_NAME}-web-secure.service=${PROJECT_NAME}-web-https
      - traefik.http.services.${PROJECT_NAME}-web-https.loadbalancer.server.port=443
      - traefik.http.services.${PROJECT_NAME}-web-https.loadbalancer.server.scheme=https
      - traefik.docker.network=traefik
    volumes:
      - ./public:/app/public
      - ./storage:/app/storage
      - ./docker/config/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/crt:/etc/ssl
    depends_on:
      - php
    networks:
      - local
      - traefik

  db:
    image: postgres:11
    ports:
      - '5432:5432'
    container_name: '${PROJECT_NAME}_db'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data/dump:/app/dump
      - ./docker/data/postgresql:/var/lib/postgresql/data
      
#Docker Networks
networks:
  local:
    driver: bridge
  traefik:
    external: true

